version: '3.8'


services:

  api:
    build:
      dockerfile: Dockerfile
      context: ./todo
    volumes:
      - /app/node_modules
      - ./todo:/app
    command: /bin/sh -c "
      rm -f tmp/pids/server.pid &&
      bundle exec rails db:create &&
      bundle exec rails db:migrate &&
      bundle exec rails s -p 3001 -b 0.0.0.0"
    ports:
      - "3001:3001"
    environment:
      - RAILS_ENV=development
  
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./todo_f
    volumes:
      - /app/node_modules
      - ./todo_f:/app
    ports:
      - "3000:3000"